export const projectsInfos = [
  {
    title: "Purples",
    subTitle: "Front-End",
    description: "",
    fctList: [
      "Fully Responsive suing TailwindCss",
      "Form validation using Formik and Yup with error feedback",
      "Auto-refetch after CUD operations using SWR",
      "Internationalization (en-ar) using i18next",
      "Calendar: appointments displaying, custom actions on click",
      "Calendar-styling: insert css using Styled-Components, and create custom component (toobar,event)",
      "Time formatting and manipulation using MomentJs",
      "Intuitive currency inputs",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MUI",
      "React-Router",
      "React-Big-Calendar",
      "Moment",
      "SWR",
    ],
    imgs: [
      "/purples-1.png",
      "/purples-2.png",
      "/purples-3.png",
      "/purples-4.png",
      "/purples-5.png",
      "/purples-6.png",
      "/purples-7.png",
      "/purples-8.png",
      "/purples-9.png",
      "/purples-10.png",
      // "/purples-11.png",
    ],
    links: {
      // github: "https://github.com/allaoua-rico/e-shop/tree/main",
      deployed: "https://mangomint-clone-olive.vercel.app/",
    },
  },
  {
    title: "Norda",
    subTitle: "MERN-stack CRUD project",
    description: "E-Commerce application made from scratch",
    fctList: [
      "Fully Responsive",
      "JWT secured endpoints and user authentication via Cookie",
      "Password reset functionnality",
      "DB protection with data sanitization",
      "Products pagination, filtering and sorting",
      "Admin product management (CRUD) with images preview , delete and add options",
      "RESTfull APIs",
      "Global error handling with Express",
    ],
    techs: [
      "NextJs",
      "TailwindCss",
      "MaterialUI",
      // "Node Js",
      "ExpressJs",
      // "MongoDB",
      "Mongoose",
    ],
    imgs: ["/e-shop2.png"],
    links: {
      github: "https://github.com/allaoua-rico/e-shop-client.git",
      deployed: "https://e-shop-iota.vercel.app/",
    },
  },
  {
    title: "Norda",
    subTitle: "Front-End",
    description: "Saloon appointment booking client view",
    fctList: [
      "Fully Responsive",
      "Appointments booking selecting time, staff and service",
      "Time formatting and manipulation using MomentJs and vanillajs date functions",
      "Usage and customization of design components from differents libraries (Mui, swiper): accordion, menu, carousels, linear progress, autocomplete, tabs.",
      "Form validation using Formik and Yup with error feedback",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MUI",
      "React-Router",
      "Moment",
      "Swiper",
    ],
    imgs: [
      "/Projects/Norda/1.png",
      "/Projects/Norda/2.png",
      "/Projects/Norda/3.png",
      "/Projects/Norda/4.png",
      "/Projects/Norda/5.png",
      "/Projects/Norda/6.png",
      "/Projects/Norda/7.png",
      "/Projects/Norda/8.png",
      "/Projects/Norda/9.png",
    ],
    links: {
      github: "https://github.com/allaoua-rico/fresha.git",
      deployed: "https://fresha-three.vercel.app/",
    },
  },
];
