export const projectsInfos = [
  {
    title: "Purples",
    subTitle: "Front-End",
    description: "",
    fctList: [
      "Fully Responsive suing TailwindCss",
      "Form validation using Formik and Yup with error feedback",
      "Auto-refetch after CUD operations using SWR",
      "Internationalization (en-ar) using i18next",
      "Calendar: appointments displaying, custom actions on click",
      "Calendar-styling: insert css using Styled-Components, and create custom component (toobar,event)",
      "Time formatting and manipulation using MomentJs",
      "Intuitive currency inputs",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MUI",
      "React-Router",
      "React-Big-Calendar",
      "Moment",
      "SWR",
    ],
    imgs: [
      "/projects/purples/purples-1.png",
      "/projects/purples/purples-2.png",
      "/projects/purples/purples-3.png",
      "/projects/purples/purples-4.png",
      "/projects/purples/purples-5.png",
      "/projects/purples/purples-6.png",
      "/projects/purples/purples-7.png",
      "/projects/purples/purples-8.png",
      "/projects/purples/purples-9.png",
      "/projects/purples/purples-10.png",
      // "/projects/purples/purples-11.png",
    ],
    links: {
      // github: "https://github.com/allaoua-rico/e-shop/tree/main",
      deployed: "https://mangomint-clone-olive.vercel.app/",
    },
  },
  {
    title: "Norda",
    subTitle: "MERN-stack CRUD project",
    description: "E-Commerce application made from scratch",
    fctList: [
      "Fully Responsive",
      "JWT secured endpoints and user authentication via Cookie",
      "Password reset functionnality",
      "DB protection with data sanitization",
      "Products pagination, filtering and sorting",
      "Admin product management (CRUD) with images preview , delete and add options",
      "RESTfull APIs",
      "Global error handling with Express",
    ],
    techs: [
      "NextJs",
      "TailwindCss",
      "MaterialUI",
      // "Node Js",
      "ExpressJs",
      // "MongoDB",
      "Mongoose",
    ],
    imgs: ["/e-shop2.png"],
    links: {
      github: "https://github.com/allaoua-rico/e-shop-client.git",
      deployed: "https://e-shop-iota.vercel.app/",
    },
  },
  {
    title: "Norda",
    subTitle: "Front-End",
    description: "Saloon appointment booking client view",
    fctList: [
      "Fully Responsive",
      "Appointments booking selecting time, staff and service",
      "Time formatting and manipulation using MomentJs and vanillajs date functions",
      "Usage and customization of design components from differents libraries (Mui, swiper): accordion, menu, carousels, linear progress, autocomplete, tabs.",
      "Form validation using Formik and Yup with error feedback",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MUI",
      "React-Router",
      "Moment",
      "Swiper",
    ],
    imgs: [
      "/projects/norda/cap1.png",
      "/projects/norda/cap2.png",
      "/projects/norda/cap3.png",
      "/projects/norda/cap4.png",
      "/projects/norda/cap5.png",
      "/projects/norda/cap6.png",
      "/projects/norda/cap7.png",
      "/projects/norda/cap8.png",
      "/projects/norda/cap9.png",
    ],
    links: {
      github: "https://github.com/allaoua-rico/fresha.git",
      deployed: "https://fresha-three.vercel.app/",
    },
  },
  {
    title: "Sapaad",
    subTitle: "Front-End",
    description: "Store cash register views",
    fctList: [
      "Dashboard: Draggable widgets (resizable and static) in a grid layout",
      "Dashboard: Data display using the graph library Recharts",
      "Usage and customization of design components from differents libraries (Mui, swiper): accordion, menu, carousels, linear progress, autocomplete, tabs",
      "Form validation using Formik and Yup with error feedback",
      "Walk-in page: Tutorial explaining the basic functionalities",
      "Walk-in page: Different menus for the different items",
      "Walk-in page: Order list with qty change, notes, add, remove actions",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MUI",
      "React-Router",
      "Moment",
      "Recharts",
    ],
    imgs: [
      "/projects/sapaad/1.png",
      "/projects/sapaad/2.png",
      "/projects/sapaad/3.png",
      "/projects/sapaad/4.png",
      "/projects/sapaad/5.png",
      "/projects/sapaad/6.png",
      "/projects/sapaad/7.png",
      "/projects/sapaad/8.png",
      "/projects/sapaad/9.png",
      "/projects/sapaad/10.png",
      "/projects/sapaad/11.png",
      "/projects/sapaad/12.png",
      "/projects/sapaad/13.png",
      "/projects/sapaad/14.png",
      "/projects/sapaad/15.png",
      "/projects/sapaad/16.png",
      "/projects/sapaad/17.png",
      "/projects/sapaad/18.png",
      "/projects/sapaad/19.png",
      "/projects/sapaad/20.png",
    ],
    links: {
      github: "https://github.com/allaoua-rico/sapaad.git",
      deployed: "https://sapaad-three.vercel.app/",
    },
  },
];
